name: Deploy home page to s3 assets
on:
  push:
    branches:
      - main
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2

        - name: Install dependencies
          run: yarn

        - name: Build
          run: yarn build

        - name: Deploy
          uses: olmesm/s3-deploy@latest
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            BUCKET: ${{ secrets.S3_BUCKET }}
            BUILD_DIR: dist
            CDN_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
            INVALIDATE_CACHE: true
            INVALIDATION_PATH: /
